### ISSUE TITLE
Create PSQL-Views for Hades

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#101]
Pycroft has to provide the Radius-Tables for Hades.

This includes (example taken from abe):

- `hades_dhcphost` (view)
- `hades_nas` (table)
- `hades_nasipaddress` (table)
- `hades_radcheck` (view)
- `hades_radgroupcheck` (table)
- `hades_radgroupreply` (table)
- `hades_radreply` (table)
- `hades_radusergroup` (view)

The creation of these tables should be Implemented using `SQLAlchemy` so `metadata.create_all` provides these tables as well.
This way, we can directly use these to run integration tests.

**Comment by lukasjuhrich** [comment]
@sebschrader IIRC you told me you started working on this. What's the state / what's the upstream branch?

**Comment by sebschrader** [comment]
As of now, there are no upstream branches yet.

**Comment by lukasjuhrich** [comment]
This can be done in two steps by postponing the complicated group query; i.e. instead of somehow joining in the information of which user should be authed and which blocked by traffic or abuse etc, a hard-coded radius group could be set.  This makes it easy to write intermediate tests.

**Comment by sebschrader** [comment]
1. Please take a look at the current `netusers` tables and views rather than the abe stuff. The abe stuff was a first attempt done in the past and is not used in production. It might work, it might now. The `netusers` stuff OTOH works well and has been improved over time.

2. I'm not sure, your two step process is worthwhile. I don't think these intermediate tests would provide much benefit. Reasoning about the views should be sufficient IMHO, but YMMV.

**Comment by lukasjuhrich** [comment]
_[half-uninformed question]_ As I recently glanced over the “actual room of a computer vs attached vlan and subnet” situation of our current `computer` relation, I noticed that we have a use case for hosts to have either a subnet/vlan not corresponding to their location, or they have two different adresses at the same time. In that case, I'm not sure which adress of both would have to be sent out via radius-reply, so this serves as a reminder for me to check that the mechanism implemented by the views allows for this use case.

**Comment by sebschrader** [comment]
Well, for RADIUS only the `VLAN` matters and for DHCP, also covered by a Hades view, that is missing in your list at the top, only the `Subnet` matters, the actual location of the `Host` is irrelevant for both. In our current Pycroft schema the way to obtain the subnet/VLAN information is via the following chain:

```
Interface n -> 1 Host n -> 1 Room 1->m SwitchPatchPort 1 -> 1 SwitchPort n -> m Subnet
```

To solve your first use case, the `SwitchPort`(s) for this room, would simple have to be in different subnets, so I don't see why 

>  hosts [would have] to have […] a subnet/vlan not corresponding to their location

We could nonetheless make a design change and cut the middle men by connecting the `Interface` directly to `SwitchPatchPort`s:

```
Interface n -> m SwitchPatchPort 1 -> 1 SwitchPort n -> m Subnet
```

Why `n:m` between `Interface` and `SwitchPatchPort`, you might ask. We possibly still have rooms with multiple ports (“valid multiple occupancies”) and we have cases, where we might want to allow the user to use additional ports (“party rooms”). Nice side effect would be, that the join chain would be shorter.

For the second use case, can you explain the use case of multiple different addresses at the same time? Maybe via chat if its sensitive information or difficult to explain?

**Comment by sebschrader** [comment]
There is also this other chain:

```
Interface 1 -> m IP n -> 1 Subnet
```

I don't think, we enforce any consistency between the `Subnet` in this chain and the `Subnet` from the chain above. This could be problematic.

**Comment by sebschrader** [comment]
Please also see #147

**Comment by lukasjuhrich** [comment]
I started working on this on the `hades` branch.

**Comment by lukasjuhrich** [comment]
The current state of affairs is that every view except `radusergroup` (which is the hard part) is implemented. Just as a reminder: This table links `nasipaddress, `

**Observation**: Logically, we only care about a mapping from users to radius groups. In no case, interfaces associated to the same user would/should yield a different group mapping. The table content just references every interface at every allowed port joined to the user. For illustration purposes, consider this sketch:

```python
        Query([]).add_columns(
            Interface.mac.label('username'),
            func.host(Switch.management_ip).label('nasipaddress'),
            SwitchPort.name.label('nasportid'),
            (VLAN.name + '_untagged').label('groupname'),
            literal(0).label('priority'),
        ).select_from(Interface)
         .join(Host)
         .join(Room)
         .join(Room.connected_patch_ports)
         .join(SwitchPort)
         .join(Switch)
         .join(Interface.ips)
         .join(Subnet)
         .join(VLAN)
```
Instead of this path, if we had some sort of mapping `(user_id, group)`, we could then join `User.hosts` and `Host.interfaces` before going the chain down to the Room etc.

## What the `(user, group, priority)` mapping consists of
The following cases should be selected:

- If the user does not have the property `network_access`, Add a generic error group (is this the one called `unknown`?)
- If the user has the property `network_access`, then add the correct vlan group with priority 0. If the user is blocked for different reasons, a higher priority should be used.
- If the user has the property `network_access` and the property `semester_fee` (which should be renamed after the finance simplifications), then check whether the current balance is `>0`(i.e. we have demands to the user): `Query([User.id]).join(Account).join(Split).group_by(User.id, Account.id).having(func.sum(Split.amount)>0)` … and add `default_in_payment`.
- If the user is traffic-limited (*Attention*: We don't yet have a mechanism for traffic exceptions! We should probably introduce a property), then the current credit (see #53 and the referenced view) should be tested for positivity. If negative, then add `traffic`
- The big question is how we find out that the user has been blocked due to a violation. There are Three possibilities:
  1. We look whether the (Config-hard-coded) group `violator_group` is in the users current groups and denies `network_access`
  2. We look for a separate propery `blocked_due_to_violation`, or `violation` (as already is created by the importer)
  3. We look for all the group memberships which had a part in denying `network_access` and use some kind of identifier as the resulting group
  There are a lot of problems in the above steps: For 1 and 3, the access would in fact not be determined solely by having the propery `network_access`: in 1, the configured group need not deny `network_access` but membership in it still causes applying the group radius group `security` with higher priority, similarly in 3 when a group granting `blocked_due_to_violation` does not deny `network_access`.
  Possibility 2 is a bit of reverse-engineering though, and we would need some kind of mapping of group id to resulting radius group.

Side note, as mentioned: I consider it a good Idea to build a view `currently_granted_properties`, because every of the above steps uses information about which properties a user currently has. Columns would be `user_id, property`, and the effect of `User.has_property()` could be realized by `SELECT exists(SELECT 1 FROM currently_granted_properties WHERE user_id=:param_1 AND property=:param_2)`. Perhaps we could even use a function for this, but such a function wuold be trivial and yet another database object effectively not providing anything new.
A meta-Advantage would be that the view would be easier to comprehend by a person debugging or trying to understand it. In general, the [following comment](https://www.postgresql.org/docs/10/static/tutorial-views.html) seems valid:
> Making liberal use of views is a key aspect of good SQL database design.

## Open Questions
Considering the types for the Columns of the tables:
- Is a Limit of the VarChars even useful?
- Should Int or BigInt be used for the `id` columns?
- What is the purpose of the `id` column? Appearently, it does not need to be unique (just take a look at the `radgroupreply` table in the netusers system), so why not just set it to 0?
- Why 
- How do we correctly incorporate `utcnow()` into the queries? If it will be inserted literally into every part of the query where we need it, the value will probably differ from instance to instance – Also, How does the usage of `now` in Views relate to this problem?

**Comment by sebschrader** [comment]
> If the user does not have the property `network_access`, Add a generic error group (is this the one called `unknown`?)

No `unknown` is for unknown users.

**Comment by lukasjuhrich** [comment]
Having in Mind I've fixed #161 locally, the tactics for `radusergroup` would be as follows:

`SELECT`
- (Interfaces of hosts of … of) Users having the property `network_access` combined with the correct radius group containing the correct VLAN name and taggedness

`UNION SELECT`
- Else (`network_access` not granted) (inner) join the properties to a new table `radius_groupname_map` (which will map certain properties like `blocking_reason_traffic` to radius group names such as `traffic`). If there are no such groups, i.e. no blocking-type property is set, add the radgroup communicating “you are not a member yet or not anymore”. I am not sure what to do if multiple such properties are set, I'm not sure how the radius would handle multiple user groups.

**Comment by sebschrader** [comment]
The unknown case is handled by Hades, you can't handle it with `radusergroup` view because you don't know the MAC address. We only have to handle the »we know you, but you don't have network access«-case.

FreeRADIUS processes the group memberships sequentially, the `Priority` field specifies the order. Processing multiple groups must be requested explicitly by settings the `Fall-Through` to `yes` in each group, otherwise FreeRADIUS will stop after the group, that did not set it. So we wouldn't actually need any if-else in the view, if the blocking priorities are higher and not `Fall-Through`.

If attributes are specified multiple times, it depends on the operator, what happens. See [this table](https://wiki.freeradius.org/config/Operators) for all the possibilities.

**Comment by lukasjuhrich** [comment]
## Current state of affairs

I finished setting up test fixtures, commits & PR incoming. Here's what it looks like:
 one: 
This follows what's about to be in `test_hades.py`
- One user with a host (with an interface bound to an ip in a subnet with a vlan)
- Three `PropertyGroup`s (member, finance, traffic)
- A membership for said user in `member` and `finance`

- Two `PatchPort`s in the user's hosts' room connected to the same switch
- `radgroup_property_mapping`s mapping the `finance` and `traffic` properties to according radius groups

### Tables

#### `radcheck`
```
     username      | nasipaddress |  nasportid   |     attribute      | op |       value       | priority 
-------------------+--------------+--------------+--------------------+----+-------------------+----------
 8a:5a:75:55:39:30 | 83.224.9.213 | SwitchPort 8 | Cleartext-Password | := | 8a:5a:75:55:39:30 |       10
 8a:5a:75:55:39:30 | 83.224.9.213 | SwitchPort 7 | Cleartext-Password | := | 8a:5a:75:55:39:30 |       10
```

#### `radgroupcheck`

```
 groupname | attribute | op | value  | priority 
-----------+-----------+----+--------+----------
 unknown   | Auth-Type | := | Accept |       10
```

#### `radgroupreply`

Sorry for the noise, I did not want to redact any table content though. For some reason the test creates five VLANs, although only two are needed.
```
    groupname    |    attribute     | op |      value      
-----------------+------------------+----+-----------------
 vlan6_untagged  | Egress-VLAN-Name | += | 2vlan6
 vlan7_untagged  | Egress-VLAN-Name | += | 2vlan7
 vlan8_untagged  | Egress-VLAN-Name | += | 2vlan8
 vlan9_untagged  | Egress-VLAN-Name | += | 2vlan9
 vlan10_untagged | Egress-VLAN-Name | += | 2vlan10
 vlan6_tagged    | Egress-VLAN-Name | += | 1vlan6
 vlan7_tagged    | Egress-VLAN-Name | += | 1vlan7
 vlan8_tagged    | Egress-VLAN-Name | += | 1vlan8
 vlan9_tagged    | Egress-VLAN-Name | += | 1vlan9
 vlan10_tagged   | Egress-VLAN-Name | += | 1vlan10
 vlan6_untagged  | Reply-Message    | += | vlan6_untagged
 vlan7_untagged  | Reply-Message    | += | vlan7_untagged
 vlan8_untagged  | Reply-Message    | += | vlan8_untagged
 vlan9_untagged  | Reply-Message    | += | vlan9_untagged
 vlan10_untagged | Reply-Message    | += | vlan10_untagged
 vlan6_tagged    | Reply-Message    | += | vlan6_tagged
 vlan7_tagged    | Reply-Message    | += | vlan7_tagged
 vlan8_tagged    | Reply-Message    | += | vlan8_tagged
 vlan9_tagged    | Reply-Message    | += | vlan9_tagged
 vlan10_tagged   | Reply-Message    | += | vlan10_tagged
```

#### `radgroupreply_base`

empty.

#### `radreply`

empty.

#### `radusergroup`

```
     username      | nasipaddress  |  nasportid   | groupname | priority 
-------------------+---------------+--------------+-----------+----------
 8e:8a:9b:14:f6:39 | 193.182.99.78 | SwitchPort 5 | finance   |       10
 8e:8a:9b:14:f6:39 | 193.182.99.78 | SwitchPort 4 | finance   |       10
 8e:8a:9b:14:f6:39 | 193.182.99.78 | SwitchPort 5 | no_member |        0
 8e:8a:9b:14:f6:39 | 193.182.99.78 | SwitchPort 4 | no_member |        0
```
The reason for `finance` is obvious, `no_member` is the catch-all group because the user misses the `network_access` property. It should only be relevant if no other blocking property results in a radius group. A good message for `no_member` would be „You are blocked for an unknown reason, or not a member yet or anymore“. If the `current_property` view could provide information about whether a property has been _rejected_, it would be possible to split this scenario up into “blocked, unknown reason” and `no_member`.

### Scenario two: user has access

#### `radusergroup`

```
     username      | nasipaddress  |  nasportid   |   groupname    | priority 
-------------------+---------------+--------------+----------------+----------
 8e:8a:9b:14:f6:39 | 193.182.99.78 | SwitchPort 5 | vlan6_untagged |       20
 8e:8a:9b:14:f6:39 | 193.182.99.78 | SwitchPort 4 | vlan6_untagged |       20
```

## Open questions

* Where do I need to set the `Fall-Through` Attribute?
* Have I used the correct operators (does `+=` work, if I never used a `:=`)?

**Comment by lukasjuhrich** [comment]
In the `radgroupreply`, I just noted a n inline TODO „Sperrgruppen haben“. Do you know what I could've meant by that? Shouldn't everything be handled by the

**Comment by sebschrader** [comment]
So first some stuff, that I noticed and you didn't ask for.

The `Reply-Message` stuff is not needed anymore. It's the legacy way of resolving the blocking reason by Hades and is not used anymore.

The column names of Hades are case-sensitive, so please use the proper case otherwise it will fail with the default configuration.

`no_member` is a bad name for not having `network_access`. Not being a member is unrelated to `network_access`. See the bottom for better names.

> Where do I need to set the Fall-Through Attribute?
I explained the semantics of this attribute earlier. If you do not want to stop processing `radgroupreply` items after a particular, the group needs to set `Fall-Through` to `yes`.

We want to ensure, that blocking groups take precedence over non-blocking groups. There are two ways to realize this:

#. Blocking groups have the highest priority (i.e. lowest value, negative values would probably be a good idea) and `Fall-Through` is set to `no` for those groups for clarity. This ensures, that the reply items of the blocking groups are applied first and evaluation stops after the first blocking group.
#. Blocking groups have the lowest priority (i.e. highest value), `Fall-Through` is set to `yes` for all non-blocking groups, and blocking groups apply the attributes with `:=` to override any previous value.

I would argue, that we go with the first option, but still set `Fall-Through` to `yes` for non-blocking groups, because there could be more than one non-blocking group.

> Have I used the correct operators (does `+=` work, if I never used a `:=`)?

I've posted a link to a table containing a description of all operators earlier. The examples you posted are correct and `+=` can be used, even if no value has been assigned previously.

> Should I add a `priority` column to the `radgroupreply` view? Because I noticed that the current hades instance multiple tables introduce a priority that sets `row_number()` over a certain window.

Hades is just very defensive and doesn't trust the data it receives. Therefore it renumbers the `priority` column to ensure uniqueness. You'll find this kind of design in several places 

> In the `radgroupreply`, I just noted a n inline TODO „Sperrgruppen haben“. Do you know what I could've meant by that? Shouldn't everything be handled by the `property_radius_group` mapping?

Yes, you need to specify what RADIUS should reply, if users are blocked. Right now, the `radgroupreply` you posted, contains no information for the blocking properties, only information for the happy path. Deriving from your example, the blocking properties are probably `finance`, `traffic`, and `no_member`, although I'm opposed to those names.

You did not post the contents of `property_radius_group` or `radgroup_property_mapping`, so I don't known, what they're doing and can only speculate. If they do a translation between `property` names and RADIUS `GroupName`, this is not necessary. The property can have the same name as the group, because Hades doesn't care (apart from the `unknown` group, which is configurable). It would only complicate things to have different names. You would need to do the reverse translation in the RADIUS logs returned from Hades via Celery. If you want to limit the properties, that are exposed as RADIUS groups, a single column table containing only the name of the properties to expose would suffice.

# Summary

* Remove `Reply-Message` reply items
* Use case-sensitive column names for Hades views
* Set `Fall-Through` to `yes` for regular groups
* Add `radgroupreply` items for blocking properties
* Use better names for the blocking properties (`traffic_limit_exceeded`, `payment_in_default`, `no_network_access`)
* Direct mapping from property name to group names

**Comment by sebschrader** [comment]
`radcheck` can be simplified to

```
     username      | nasipaddress |  nasportid   |     attribute      | op |       value       | priority 
-------------------+--------------+--------------+--------------------+----+-------------------+----------
 8a:5a:75:55:39:30 | 83.224.9.213 | SwitchPort 8 | User-Name | =* |  |       10
 8a:5a:75:55:39:30 | 83.224.9.213 | SwitchPort 7 | User-Name | =* |  |       10
```

which we're currently using.

**Comment by lukasjuhrich** [comment]
But setting `Fall-Through` to `no` for blocking groups contradicts that I have to set it to `yes` so multiple group memberships are possible for a user, or are there multiple levels where I can apply `Fall-Through`?
