### ISSUE TITLE
Enforce / Recommend MAC uniqueness

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#121]
Whenever a new, “simple” `UserHost` is created – i.e.,  A `UserHost` with one `Interface` having a given MAC, there should be checks that the MAC address is unique or at least a warning that it exists.

The question is, when are multiple interfaces with the same MAC address a problem? Does it only affect people who are currently members? (note: when moving out, all the hosts are deleted.) What if one is suspended due to violation? What if two such coinciding users live in the same room?

I don't think this can be encoded in the model directly, but the library should be able the obvious case of two active users with the same address (and the frontend as well).

**Comment by sebschrader** [comment]
Non-unique MAC addresses are a problem if both hosts belong to users that are allowed to have network access and are in the same subnet.

This is difficult to enforce by the schema, because the database would have to perform membership lookup. 
We could instead, use a more strict approach and enforce either

1. Globally unique MAC addresses regardless of group memberships.
2. Unique MAC address per subnet regardless of group memberships.

The first restriction can be realised with an UNIQUE constraint, the second with an EXCLUDE constraint (generalised UNIQUE constraint):

http://thoughts.davisjeff.com/2010/09/25/exclusion-constraints-are-generalized-sql-unique/

A user manager would then have to resolve conflicts by hand during user/host creation and movement.

**Comment by mmarx** [comment]
Please keep in mind that non-unique MAC addresses in hardware devices do happen (although it's been a while since I've seen that). In that light, enforcing uniqueness only per subnet seems to be the better option.

**Comment by toothstone** [comment]
Due to people trading routers this actually happens quite often, and is currently quite a nuisance, since you have to find the previous owner and assign a different MAC to him before you can enter the MAC for the new owner.

**Comment by mmarx** [comment]
Most of these cases should be covered by people moving out getting their accounts deleted. Apart from that, it would certainly be helpful to display the conflicting hosts (and maybe add an option to delete it/replace the MAC with a dummy address/etc.)

**Comment by sebschrader** [comment]
It might be nuisance @toothstone, but it has to be done. We can't have multiple devices with the same MAC address active at the same time in our database. Hades, for example, will vigorously defend itself against duplicates in its data and select one of the records and drop all others.

It's more of an UX issue. If the user creation form would show conflicts before submit and offer an option to automatically change the ownership of a device, that already exists in our records, from the old user to the new.

But, I would suggest you open a new issue for this feature.

**Comment by lukasjuhrich** [comment]
@sebschrader Concerning the Exclusion constraint, we should talk about it, something along the lines of “give me all MAC addresses of devices which have an interface which has an IP in this subnet and check whether the MAC in question is in there” would not be sufficient: It could be possible that the cause is not another host, but _the very host we want to assign the IP to_, if it already has a different IP address in the same subnet.

**Comment by sebschrader** [comment]
We should not overthink this. Duplicate MACs in the sense of different physical devices with the same MAC address are very, very rare and shouldn't happen if vendors don't screw up.

On my watch for example, this never happened, but it happened in the past with some Chinese network interface cards. If this rare case should happen, we will find way to resolve. On OS X and Linux you can change your MAC addresses anyway and on Windows many drivers offer an option under the `Advanced` tab (and there is also Registry setting, which will work for every card, there is just no UI for it). Besides, most users have residential gateways now instead of a desktop PC, which allow you to change the MAC address.

So just like air lines and hotels handle overbooking and bank allow you to withdraw money to some degree from an ATM even if they have no access to the banking network, we should handle these rare issues on a business level rather than a technical level.

Therefore, I suggest we simply create a `UNIQUE` constraint on the `mac` column of `interface` table. As stated earlier @toothstone's problem is mainly an UX issue. We should therefore handle conflicts during user/host creation and offer an option to change the ownership of the existing `interface`.

**Comment by mmarx** [comment]
Yes, exactly.

**Comment by lukasjuhrich** [comment]
Since @ibot3 is working on the UX issue (#138), I also propose the global `UNIQUE` constraint, leaving us with the following tasks:

- [ ] Add unique constraint
- [ ] Add logic to the importer that does not add the device from the non-active or older user

**Comment by lukasjuhrich** [comment]
The unique constraint will require a lot of prep work, as currently there are 145 interfaces whose mac exists ≥ twice.
Most occurrences can probably be dealt with by deleting hosts of users with state „Gesperrt (Ausgezogen)“, but note that this will probably also require some maintenance over time.

**Comment by sebschrader** [comment]
That's to be expected, but maybe we can offload the cleanup work to some of our colleagues. Could you generate the list, send it around on one of the mailing lists, and ask if someone will take care of it.

**Comment by lukasjuhrich** [comment]
I stand corrected. By removing the Host, and not only the IP, for all the inactive user states, this reduces to two macs for five persons.
I don't see any good way to make the importer intelligent enough to not add hosts  of other users; It is designed to add every host by itself and is not capable of deleting objects once added to the big list.
I propose to just cope with the duplicates manually.
