### ISSUE TITLE
Export properties as LDAP groups

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#126]
The LDAP syncer should be able to sync a configurable subset of the granted (or denied) properties to `nestedGroupOfNames` so services can test for membership.

**Comment by sebschrader** [comment]
I have never heard of `nestedGroupOfNames` and Google confirms that are probably is no such thing. You can always nest groups in LDAP by setting the member attribute to the DN of another group instead of a user.

Furthermore we should not use `groupOfNames` and use `groupOfMembers` from RFC2307bis instead. `groupOfNames` has some nasty disadvantages:

1. It's a structural rather than an auxiliary class, thus you can't combine it with other classes such as `posixGroup` that are structural too.

2. The member attribute is required, i.e. you must have at least one member per group.

**Comment by lukasjuhrich** [comment]
@sebschrader Could you please address this question? It is important for the planning to know whether this feature is a “Bare Minimum” or can be postponed.

**Comment by sebschrader** [comment]
>@sebschrader Could you please address this question? It is important
>for the planning to know whether this feature is a “Bare Minimum” or
>can be postponed.

The example you gave, can be addressed. The `aktiv` group can simply be converted into a *local UNIX group* on atlantis. Group membership in this group is already managed manually. Doing it in `/etc/group` or LDAP doesn't make much of a difference, if any.

There are other areas, where I don't have a good solution. Without manual managed blacklists on the respective system, we can only exclude users from or all or none of our services with the current mechanism by *denying the LDAP export property*. If the system distinguishes between “account not found” and other authentication errors, the user would temporarily get an “account not found” error.

In particular that means, we can't easily deny him login rights to `userlogin` while retaining his right to receive mails. Receiving mails is the most problematic case, I could think of. You don't want to temporarily reject someone's mails with a permanent error, because mails would immediately bounce. Not that we're making use of it very often, but you also couldn't use the user's mail address to contact him anymore.

If there is a way to address the mail issue or we can live with the fact, that we can't revoke someone's access to other services, that make use of LDAP, while retaining his mail service, we are fine otherwise it's a blocker.

**Comment by mmarx** [comment]
How about using `pam_check_host_attr` to restrict login to certain hosts?

**Comment by sebschrader** [comment]
> How about using `pam_check_host_attr` to restrict login to certain hosts?

Using the `host` attribute has always been bit of a hack, I'd prefer to use local Unix groups, if it makes sense (`Aktiv` on atlantis). For locking out users, the [`passwd --lock`](http://man7.org/linux/man-pages/man1/passwd.1.html) mechanism, which makes the password invalid by prefixing it with a exclamation mark `!`, together with an appropriate `shadowExpire` to ensure login via SSH keys is not possible, can be used with LDAP too.

Additionally, I just came across [OpenLDAP's password policy overlay](https://www.openldap.org/doc/admin24/overlays.html#Password%20Policies), which is worth taking a look. After defining a proper default policy and a policy for disabled users, which boils down to creating two `pwdPolicy` objects, all that needs to done, is add the `pwdPolicySubentry` attribute pointing to the policy for to disabled users, to a disabled user.

To conclude: The LDAP exporter in Pycroft needs to determine, which users should be exported, but be disabled and add appropriate `userPassword`, `shadowExpire`, and `pwdPolicySubentry` attributes to these users.

**Comment by lukasjuhrich** [comment]
closed in #297
