### ISSUE TITLE
Remove different patch port types

### ISSUE THREAD

**Issue by sebschrader** [agdsn/pycroft#142]
Similar to #139 the patch port hierarchy can be removed.

The only point of this hierarchy was to distinguish patch panel ports, that are connected to switches, from patch panel ports, that are connected to phone patch panel ports (RJ11/RJ14). This can also be accomplished by making the `switch_interface` (after solving #139 `switch_port`) column `nullable`.

This has the benefit, that ports can easily switch between being attached to a switch or not, which happens sometimes, if the original line is broken. Also, ports, which are connected neither to a switch nor a port, can be modeled.

A `comment` column should be added, for an optional description of the current circumstances (e.g. »broken« or »connect to phone patch panel«). Maybe, a `PatchPortLog` should be added too?

**Comment by lukasjuhrich** [comment]
I suggest we should neither add a `comment` nor introduce a `PatchPortLog` atm, because that's the kind of information that the `RoomLog` already can capture, and that is more or less exactly the reason for its existence.
We can always change it later if the demand for more structured logging on this side appears, however I doubt that'll happen.

**Comment by sebschrader** [comment]
I disagree, we definitely need a comment, if we remove the phone patch port class. The log would definitely be optional and maybe a bit controversial, because as you said, the room log can be used for this purpose too.

However, there must be a way to denote the fact, which ports are connected to a phone patch panel.

Just the fact, that they are not connected to a switch is not enough. We also have ports that are simply unused. This is also a deficiency of the current model, because it can't model this properly.

**Comment by lukasjuhrich** [comment]
I began implementing this change, but I will postpone it. A lot of library code just iterates over _connected_ patchports and thus expects the non-nullability of `SwitchPatchPort.switch`, which is why just lifting `SwitchPatchPort`→`PatchPort` and renaming the relationship to `Room.patch_ports` makes it useless, because said nun-nullability is lost.

When tackling this issue again, the plan would be to drop the `(switch_)patch_ports` backref and introduce a secondary relationship `Room.switch_ports` that just skips the `PatchPort`s.

**Comment by sebschrader** [comment]
Wouldn't defining two different relationships on room to patch port, one with all ports of this room and one that excludes ports with a null switch suffice? You can add conditions to a relationship.

**Comment by lukasjuhrich** [comment]
Where? I only read about conditions in arguments usable for secondary joins or some more complicated matter

**Comment by sebschrader** [comment]
Yup, exactly this feature. If it can be used to join arbitrarily many tables together, it can also be used for something much simpler. The docs contains an example that limits addresses to city for example:

http://docs.sqlalchemy.org/en/latest/orm/join_conditions.html#specifying-alternate-join-conditions

**Comment by sebschrader** [comment]
Further below you can even see an example of an IP to subnet relationship using the contains operator of PostgreSQL, I talked about earlier!
