### ISSUE TITLE
Display users with group "Extern" by default in the level view

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#151]
Since we need to do support for non-members, they should also show up in the default level view.

**Comment by toothstone** [comment]
I just learned from @lukasjuhrich that this is a repetition of #105. However I'm not happy with the fix or rather workaround implemented there.

If "Extern" has to be hardcoded so be it, isn't "Mitglieder" hardcoded as well?

**Comment by sebschrader** [comment]
> If "Extern" has to be hardcoded so be it, isn't "Mitglieder" hardcoded as well?

I hope not.

**Comment by lukasjuhrich** [comment]
@sebschrader by hard-coding, @toothstone means adding it to the `Config`.

**Comment by sebschrader** [comment]
My earlier point still stands. The overview page should use properties, like “network access” instead of groups to decide which users to display.

The “network access” on its own may not be enough, maybe some others should be used too.

Also one might want to ignore “deny entries” for this property and only look for “grant entries” to include users, who are currently blocked. This is the only missing facility in our code, IMHO.

Directly using groups subverts the whole properties system.

**Comment by lukasjuhrich** [comment]
Depending on whether it's still an issue, one could easily add a `show_in_room_overview` property which gets checked by default; the „show all” switch could remain as it is and provide a complete view of all users.

**Comment by lukasjuhrich** [comment]
This is not an issue anymore: we currently
- by default: list everyone who has `network_access` (granted _or_ denied) – this includes members of the `Extern` group
- with `all users` toggled: list everyone.
