### ISSUE TITLE
Generalize "Wohnheim" to location

### ISSUE THREAD

**Issue by Lodifice** [agdsn/pycroft#305]
Currently, it is impossible to manage external residences in Pycroft. However, storing this data is required by law. The "Wohnheim"/building system could be generalized so that they represent locations, then a new location Dresden can be created having addresses rather than room numbers.

**Comment by gehinz** [comment]
This issue is important, as the Abe importer will add members that require this type of address.

**Comment by toothstone** [comment]
I think a complete generalization would be best here, so that we don't run into further constraints in the future. The address associated with an user (user as in using TKG regulated resources or for whom we have similar obligations to be able to identify them) should imho be the standard Street-Street number-Additional Field (Room number!)-ZIP Code-City-State-Country kind of object.

For most users, this can be auto-filled from the host location from the current location scheme, so it shouldn't cause any support overhead, like many online shops handle multiple addresses in the 'delivery address different from invoice address' way.

**Comment by lukasjuhrich** [comment]
I think auto-filling things and enforcing a format would be an overcomplication. A simple string field would suffice. One could just do the following:

- Add `User.address: str` (default `null`)
- Add a check constraint which verifies that either `room_id` or `address` is set.

That way, we already satisfy the legal requirements, required that our administrators take care of filling the fields with an actual address and not a bogus value. Furthermore, there is no advantage to letting the `address` field know anything about the technicalities of how pycroft understands rooms, or filling this col even if the user has a room.[1]

The rest would 
- Implement `pycroft.lib.user.change_address` (either empty string resets or +unset_address)
- Raise useful error messages in the moving-out related library routines if this validation fails
- Display the address in the UI (prob. near the room or even in the same field.)

[1] Although when implementing this change, we should probably make sure to unset the room for those individuals who live in a rack or the basement (hosts will work anyway as they have their own reference to a room) so we will notice the lack of address there.

**Comment by Lodifice** [comment]
Honestly, reading your suggestion I feel it adds more complexity than the redesign @toothstone suggested. So I'd opt for the redesign, but feel free to do it the way you like.

**Comment by mmarx** [comment]
> Honestly, reading your suggestion I feel it adds more complexity than
> the redesign @toothstone suggested. So I'd opt for the redesign, but
> feel free to do it the way you like.

This: disjunctive constraints usually incur an additional complexity cost (although it might be fine in this specific case), so there is something to avoid introducing them to the schema.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lukasjuhrich** [comment]
Sure, there is _some_ amount of (imo pretty limited) complexity.

But in my defense, I am pretty certain that at least the same amount of complexity would be found in @toothstone's proposition once it would be given as an _actual, technical proposal_ instead of some vague outlining. There's multiple ways to „associate“ things in a database, and the two specific solutions I can think of would either require polymorphism or redundancy (both a nullable room and a non-nullable address-FK on a user, where the latter would have to be synced on every room-related change – if you trust the lib – or with multiple triggers on the right location).

@Lodifice's initial idea that „The "Wohnheim"/building system could be generalized so that they represent locations“ is also pretty unclear to me or sounds like a complete hack (On which level do you want to split the Room → Building → Site chain up? And if you don't wanna do that, do you plan on making `User.room` non-nullable and adding a fake “Dresden” site with a fake “Generic Building” building with rooms all on level 0 and the actual addresses in the `Room.number`? That seems like an awful lot of complexity for what could be just some semi-optional string content.)

I'll probably start implementing this tomorrow, but I'm open for further discussion.

**Comment by mmarx** [comment]
> There's multiple ways to „associate“ things in a database, and the two specific solutions I can think of would either require polymorphism or redundancy (both a nullable room and a non-nullable address-FK on a user, where the latter would have to be synced on every room-related change – if you trust the lib – or with multiple triggers on the right location).

Add a fresh relation for Addresses, comprising the fields listed by @toothstone, and use that as a non-nullable foreign key in both Users and Rooms. This has the additional benefit of allowing rooms to have multiple addresses, which is useful when, e.g., street names are changed.

**Comment by lukasjuhrich** [comment]
Concerning the problem that #67 remains to be implemented, we have the following problematic use cases:

1. Moving out a user: What should his address be? Preferably after #67, the classic „move out“ should delete a user, and and alternative should be provided to keep the user while requiring an address.
2. Migrating the current users without a room: What should their Address be? We should probably go through that list and delete all of those, however that requires a quick look on whether the cascades work correctly.

There are two possibilities:
1. Making the FKey `User→Address` optional
2. As a workaround, using a designated address signifying that users having that room are obsolete.

I know 2. is ugly, but making the FKey optional has the disadvantage that this would have to be changed at _some_ point (probably after implementing #67), and I would rather settle the orphan situation without the pressure of a failing migration, which imposes a blocker on new features.

**Comment by lukasjuhrich** [comment]
Also, the use case of adding rooms (e.g. because we're adopting another dormitory) will require double the effort, because prior to creating the rooms, the addresses have to be created as well, with some redundant information. There's no great way around this AFAICS.

**Comment by lukasjuhrich** [comment]
Note the design decisions I outlined in [this PR comment](https://github.com/agdsn/pycroft/pull/338#discussion_r331463505).
