### ISSUE TITLE
Improve infrastructure navigation

### ISSUE THREAD

**Issue by lightning1** [agdsn/pycroft#335]
Changes to the infrastructure settings (subnets, switches, vlans) of pycroft are sometimes hard to catch, especially if patchports are involved.
I can think of the following improvements:
* User-View: use "switch" in the host table as a direct link to the related switch page
* Switch-View: add "+ Patch-Port" button (this is currently only reachable via the room where the switch resides)
* Room-View: add "+ Patch-Port" button

**Comment by lukasjuhrich** [comment]
I am working on the first two, but I would like to reject the third point, because
- it's not really worth it: creating patch ports happens en masse with a database import
- it's harder to implement: this is the first „patch port creation“ where one has given the target room and is selecting the switch room instead of vice versa; so we cannot re-use the existing endpoint/form. This adds complexity for a rare use-case
