### ISSUE TITLE
Regression: allow creation of users without a room

### ISSUE THREAD

**Issue by ibot3** [agdsn/pycroft#428]
It should be possible to edit the address of a user and the address of a room.

Furthermore, creating a user without room is currently not possible, because no address is set. We could either use a dummy address or add the address fields to the user create form.

**Comment by lukasjuhrich** [comment]
Refs #344

**Comment by lukasjuhrich** [comment]
Are membership requests without a `room` relevant to us in any way?
`create_member_request` does not enforce that a `room` is set.
If I understand correctly such requests could never have been parsed since there is no way for an address to be specified.

The Background is that I would like to avoid adding even more cludder (read: 5+ input forms for the address) to our generic user creation form, and instead split things up into the two use cases
1. Creating a new user in a known room (perhaps even removing this largely useless membership select field)
2. Creating an external user, requiring specification of an address.

**Comment by lukasjuhrich** [comment]
Also, why is the email [suddenly required](https://github.com/agdsn/pycroft/blob/7005136b68038907a22fdca101faf012df4bd6c2/web/blueprints/user/forms.py#L116) when editing members, but `PreMember.email` is nullable? What's the right constraint here?

**Comment by ibot3** [comment]
The email should be required for a member request. If that's not enforced by pycroft, it is probably a mistake.

Member requests can have the room set to `None` for some time. However, for transforming a member request to a user, a room is required.

**Comment by lukasjuhrich** [comment]
Fixed by #433
