### ISSUE TITLE
“+1GiB” Button

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#53]
A button resetting the credit of a member to +1GiB would be useful.

Thanks @toothstone for the suggestion!

**Comment by lukasjuhrich** [comment]
This is more or less blocked by the implementation of determining the current credit, which is (or should be) one of the changes introduced in #112

**Comment by lukasjuhrich** [comment]
If I recall correctly (correct me if I'm wrong @Georgeto), the plan was to create a View at least for the current traffic balance of the User.  My plan would be implementing this View plus adding a hybrid property to the `User` model and testing this. This leaves implementation of the correcting entry rather simple.

**Comment by sebschrader** [comment]
The view was part of the plan, as I recall and is a very good idea in any case. The current balance is needed in many places and using a view allows us to abstract the necessary computation away in the database instead of a library function. It also allows us to optimize the computation later, if necessary.
