### ISSUE TITLE
HTML tags in plain text "Change of residence" notification email

### ISSUE THREAD

**Issue by FestplattenSchnitzel** [agdsn/pycroft#625]
Some examples:

```txt
<pre>
English version below!
--
Du kannst deinen Netzwerkanschluss nach vorherigem Login auf unserer <a href=["https://agdsn.de/sipa/usersuite/"](https://agdsn.de/sipa/usersuite/)>Internetseite</a>
freischalten.
```

Seems like all links are present with an `<a>` tag around.

**Comment by lukasjuhrich** [comment]
The reason is that someone did not use the `render_link` macro in the template, which would look like this: https://github.com/agdsn/pycroft/blob/5042fb71e7564b7cf75afcc3ca6e65dd49f26873/pycroft/templates/mail/user_created.html#L27-L30

For instance, in `user_moved_in.html`, someone left a plain `<a>` tag: https://github.com/agdsn/pycroft/blob/5042fb71e7564b7cf75afcc3ca6e65dd49f26873/pycroft/templates/mail/user_moved_in.html#L20-L21
