### ISSUE TITLE
Import throttling and internet_by_rental flags

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#81]
Currently, the importer doesn't map the following information:

- throttling
- internet_by_rental: Given in `wheim` and `nutzer`.  For the users, when `nutzer.internet_by_rental` is True, it should not be given a membership in the `member` group, but in some other describing an external user (no need to pay etc.)

**Comment by lukasjuhrich** [comment]
@lightning1 @sebschrader could one of you who knows it clarify how the throttling is applied? Is this information included in the views for the radius server? Technically, every `nutzer` could be changed to the `throttled` state, regardless of where he_she lives.

**Comment by sebschrader** [comment]
The throttling status was added to test throttling with our switches to throttle instead of disabling the network access entirely. Because, not all our infrastructure supports it, we did not use it as a replacement for the regular traffic limit exceeded status.

You don't need to map the throttling status and handle it like any other unknown value. I presume an exception would be thrown and the import is aborted instead.

**Comment by lukasjuhrich** [comment]
@sebschrader that is the throttling status for a user. I presume the throttling flag in the `wheim` is irrelevant then?

As it appears, the status 13 leads to a KeyError as it is not included in the current mapping, so you're correct.

**Comment by sebschrader** [comment]
I don't know about this flag. May be we intended to roll out throttling only for the sites, where the switches support it, but I don‘t recall it.

**Comment by lightning1** [comment]
@lukasjuhrich sebschrader is correct. The activation of the status via JUserman works only for users on switches that supports throttling. So the flag in `wheim` provides information about the capabilities of the switches at this side.
I suggest ignoring this, since throttling is not going not be implemented via switches.

**Comment by lukasjuhrich** [comment]
Note to self: This will require adding a new property group „Èxterner Nutzer“ which solely enables the network access and doesn't affect anything else – such persons can become a DSN member as well very easily.

**Comment by lukasjuhrich** [comment]
Blocked by #87
