### ISSUE TITLE
User-ID Checksums: Display in overview

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#96]
Currently, the concept of a User-ID checksum does not exist.  If pycroft will be used for importing and thus matching finance data, it should be able to parse it. Even more importantly, the legacy digit sum should be supported as well.

**Comment by sebschrader** [comment]
This is not correct. The current checksum scheme has already been implemented and I've also created a new, much more robust (not susceptible to digit swapping) checksum scheme based on the IBAN scheme used on international bank account numbers. The new scheme also has also two check digits, so that it can be used simultaneously with the legacy scheme.

**Comment by lukasjuhrich** [comment]
@sebschrader Alright, this reduces this issue to the mere displaying in the overview! 😎
