### ISSUE TITLE
Display saldo under Stammdaten

### ISSUE THREAD

**Issue by toothstone** [agdsn/pycroft#97]
The saldo should appear with the other vital information at the top, this could replace the "Bezahlt"-flag.

**Comment by lukasjuhrich** [comment]
I have a quickfix soon to be pushed to `radius_logs`, however, the “overview” section should be restructured completely. This has been hinted at by Issues #2 #31 #40 #46, concerning mostly the buttons on the right. In addition to that, I think it would be a good Idea to simplify the left `<dl>` as well, and for instance use icons to simplify identification (e.g. try to find whether the user has paid and ask yourself how easy that was).

Concerning the fix: I added the saldo below the “ja/nein” lines, which is redundant to the “Bezahlt: ja/nein” line. I didn't want to change something there because it would probably be changed anyway in the long run.
