### ISSUE TITLE
Phrase “mail access” like “access to services”

### ISSUE THREAD

**Issue by lukasjuhrich** [agdsn/pycroft#98]
Although at the present time, the most important thing about having an LDAP account is the email access, I find it more appropriate to refer to this as “access to services”. Firstly, having an LDAP account also gives access to the webhosting over at [users.agdsn.de](https://users.agdsn.de/), and secondly, this might be expanded in the future, since Pycroft aims to provide a central member's LDAP.

Therefore, I propose to change the descriptions referring to “mail access” to “access to services”, and renaming the property `mail` to `services`.

Perhaps this should be done before the first deployment as this would imply a small, but significant structural change (concerning the static contents in the `config` table).

**Comment by sebschrader** [comment]
Specific properties for specific services would be the best thing.

**Comment by lukasjuhrich** [comment]
@sebschrader I disagree. This would be an unnecessary refactoring burden and there is no real disadvantage in bundling the access to one property.

**Comment by sebschrader** [comment]
The whole point (or one important) of properties is to have a very granular mechanism instead of a tight coupling of our policies with our code.

Besides, none of the Pycroft code, should actually need to know about the properties our mail system or our public login server. They verify their properties (through an eventual LDAP export) and pycroft verifies its properties.

**Comment by lukasjuhrich** [comment]
I am not sure I agree this is worth the effort. We have never handled our services separately, either you had a unix account and thus access to `userlogin`, the userhosting, your mailbox, and the userdb, or you didn't. Currently however, naming it `mail` is misleading and wrong, as it represents more than just access to mail, and without reimplementing a whole lot of logic, renaming it would be the more rational option.

**Comment by sebschrader** [comment]
If adding new groups and properties is such a big effort, then clearly something is very wrong.

There are some groups that are special to Pycroft, i.e. the ones referenced by the `Config` model class.
Changing or adding those is clearly an effort, but this by design and ok. They are special to Pycroft, because Pycroft automatically manages group memberships in these groups. Other, manually managed groups, should however always be possible.

Adding new properties on the other hand, should never be a problem. If other services want to leverage Pycroft's property system, the should be able to do so. We can always add properties to the `member_group` for example and Pycroft won't care.

**Comment by lukasjuhrich** [comment]
I understand your point now.

I found the following occurrences of “hard-coding” the mail attribute:
- `lib.user`, in `status()` and `status_query()` (the logic providing the letter-icon in the status buttons)
- `model.property`, in the hard-coded property categories. These only provide descriptions.

**Comment by lukasjuhrich** [comment]
I fixed this in a current branch of mine, however I named the propery `ldap` and the descriptions “has an LDAP account”. naming it “services” and „Has access to services“ would suggest that getting this flag would imply access to some (if not all) services, which need not be the case – if we in fact encode the permissions in other attributes, then having the “ldap” flag does not necessarily grant access to any service in particular.
